name: VAA
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # (Optional CUDA runtime if you want conda to manage it)
  # - cudatoolkit=12.4
  # - cudnn
  - pytorch=2.5.*  # helps conda solve MKL + CUDA deps
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - numpy=1.25.*
  - scipy=1.9.*
  - scikit-learn=1.1.*
  - pip:
      - absl-py==2.2.2
      - accelerate==0.26.0
      - ace_tools==0.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - av==14.2.0
      - beautifulsoup4==4.13.3
      - bertopic==0.16.4
      - bitsandbytes==0.45.1
      - bleach==6.2.0
      - blis==1.2.0
      - blobfile==3.0.0
      - Bottleneck==1.4.2
      - braceexpand==0.1.7
      - Brotli==1.0.9
      - catalogue==2.0.10
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.20.0
      - coloredlogs==15.0.1
      - comm==0.2.2
      - confection==0.1.5
      - contourpy==1.3.1
      - crcmod==1.7
      - cryptography==44.0.1
      - cycler==0.11.0
      - cymem==2.0.11
      - datasets==3.6.0
      - debugpy==1.8.14
      - decorator==5.1.1
      - decord==0.6.0
      - deep-sort-realtime==1.3.2
      - deepsort==0.0.5
      - dill==0.3.6
      - distro==1.9.0
      - einops==0.8.0
      - en_core_web_sm==3.8.0
      - exceptiongroup==1.2.0
      - executing==2.1.0
      - fairscale==0.4.13
      - faiss-gpu==1.7.2
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - filelock==3.14.0
      - fire==0.7.0
      - flash-attn==2.7.2.post1
      - flatbuffers==25.1.24
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.12
      - GitPython==3.1.44
      - gmpy2==2.2.1
      - grpcio==1.71.0
      - h11==0.14.0
      - h5py==3.12.1
      - hdbscan==0.8.40
      - httpcore==1.0.2
      - httpx==0.27.0
      - huggingface-hub==0.30.2
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - importlib_metadata==8.6.1
      - importlib_resources==6.4.0
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.35.0
      - jedi==0.19.2
      - Jinja2==3.1.5
      - jiter==0.6.1
      - jmespath==0.10.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language_data==1.3.0
      - llvmlite==0.44.0
      - lxml==5.3.1
      - marisa-trie==1.2.1
      - MarkupSafe==2.1.3
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mkl_fft==1.3.11
      - mkl_random==1.2.8
      - mkl-service==2.4.0
      - modelscope==1.23.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.14
      - murmurhash==1.0.12
      - narwhals==1.26.0
      - nest_asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numba==0.61.0
      - numexpr==2.10.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.20.1
      - openai==1.60.1
      - opencv-python==4.11.0.86
      - openxlab==0.1.2
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.2.3
      - parameterized==0.9.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==25.0
      - platformdirs==4.3.7
      - plotly==6.0.0
      - ply==3.11
      - portalocker==3.1.1
      - preshed==3.0.9
      - prompt_toolkit==3.0.51
      - propcache==0.2.0
      - protobuf==4.25.3
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pycryptodomex==3.22.0
      - pydantic==2.10.3
      - pydantic_core==2.27.1
      - Pygments==2.19.1
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - PyQt5==5.15.10
      - PyQt5_sip==12.13.0
      - PySocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-slugify==5.0.2
      - pytorchvideo==0.1.5
      - pytz==2023.4
      - PyYAML==6.0.2
      - pyzmq==26.2.0
      - qwen-vl-utils==0.0.10
      - RapidFuzz==3.12.2
      - regex==2024.11.6
      - requests==2.32.4
      - responses==0.13.3
      - rich==13.4.2
      - rouge-score==0.1.2
      - safetensors==0.4.5
      - seaborn==0.13.2
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - setuptools==60.2.0
      - shellingham==1.5.4
      - sip==6.7.12
      - six==1.16.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.0
      - socksio==1.0.0
      - soupsieve==2.6
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack_data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - text-unidecode==1.3
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - timm==1.0.15
      - tokenizers==0.20.3
      - tomli==2.0.1
      - triton==3.1.0
      - typer==0.15.1
      - typing_extensions==4.12.2
      - tzdata==2023.3
      - ultralytics==8.3.71
      - ultralytics-thop==2.0.14
      - umap-learn==0.5.7
      - unicodedata2==15.1.0
      - Unidecode==1.3.8
      - UpSetPlot==0.9.0
      - urllib3==1.26.20
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.111
      - webencodings==0.5.1
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==1.17.2
      - xformers==0.0.28.post2
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.18.0
      - zipp==3.21.0
